#!/bin/bash

create_link()
{
    rm -rf ~/.$1
    ln -s ~/.dotfiles/$1 ~/.$1
    echo -e "\e[1;32mCréation du lien symbolique $1\e[0m"
}

create_link alacritty.yml
create_link zshrc
create_link gvimrc
create_link vim
create_link vimrc
create_link tmux.conf
create_link gitignore
create_link gitconfig
create_link gtkrc-2.0
create_link icons
create_link config/i3
create_link config/rofi
create_link config/gtk-3.0
create_link config/polybar
create_link config/dunst
create_link config/alacritty
create_link config/nvim

