#!/bin/bash

create_link()
{
    rm -rf ~/.$1
    ln -s ~/.dotfiles/$1 ~/.$1
    echo -e "\e[1;32mCréation du lien symbolique $1\e[0m"
}

create_link zshrc
create_link gvimrc
create_link vim
create_link vimrc
create_link tmux.conf
create_link gitignore
create_link gitconfig
create_link config/terminator
create_link config/i3
cd ~/.dotfiles
git submodule init
git submodule update
